---
- name: "zones | Manage Custom Firewall Zones - create/delete"
  ansible.posix.firewalld:
    permanent: "{{ item['permanent']|default(true) }}"
    state: "{{ item['state'] }}"
    zone: "{{ item['zone'] }}"
  become: true
  with_items: '{{ firewalld_custom_zones }}'
  notify: reload firewalld service

- name: "zones | Manage Custom Firewall Zones - target"
  ansible.posix.firewalld:
    permanent: "{{ item['permanent']|default(true) }}"
    state: "{{ item['state'] }}"
    target: "{{ item['target']|default('default') }}"
    zone: "{{ item['zone'] }}"
  become: true
  with_items: '{{ firewalld_custom_zones }}'
  notify: reload firewalld service
