---
- name: zones | Manage Custom Firewall Zones
  firewalld:
    zone: "{{ item['zone'] }}"
    state: "{{ item['state'] }}"
    permanent: true
  become: true
  with_items: '{{ firewalld_custom_zones }}'
  notify: reload firewalld service

- name: zones | Flush pending handlers (reload firewalld)
  meta: flush_handlers
