---
- name: debian | Checking If UFW Is Installed
  command: "dpkg -s ufw | grep Status"
  become: true
  changed_when: false
  failed_when: false
  register: "_firewalld_ufw_check"

- name: debian | Disabling UFW If Installed
  service:
    name: "ufw"
    state: "stopped"
    enabled: false
  become: true
  when: >
        'installed' in _firewalld_ufw_check['stdout']

- name: debian | Installing Firewalld
  apt:
    name:
      - 'firewall-config'
      - 'firewalld'
    state: "present"
  become: true

- name: debian | Ensuring firewalld Service Is Started And Enabled On Boot
  service:
    name: "firewalld"
    state: "started"
    enabled: true
  become: true

