---
# tasks file for ansible-firewalld
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: custom_zones.yml
  when: firewalld_custom_zones is defined

- include: zones.yml
  when: firewalld_zones is defined

- include: rules.yml
  when: firewalld_rules is defined

