---
# tasks file for ansible-firewalld
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: custom_zones.yml
  when: firewalld_custom_zones is defined

- include_tasks: zones.yml
  when: firewalld_zones is defined

- include_tasks: rules.yml
  when: firewalld_rules is defined

