---
# tasks file for ansible-firewalld
- name: "main | Include tasks specific for Debian os family"
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: "main | Include tasks specific for RedHat os family"
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: "main | Ensuring that ssh port number is configured before starting firewall"
  template:
    src: "etc/firewalld/services/ssh.xml.j2"
    dest: "/etc/firewalld/services/ssh.xml"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true

- name: "main | Ensuring firewalld service is started before configuring zones & rules"
  ansible.builtin.service:
    name: "firewalld"
    state: "started"
  become: true

- name: "main | Include tasks for managing custom firewall zones"
  include_tasks: custom_zones.yml
  when: firewalld_custom_zones is defined

- name: "main | Include tasks for managing common firewall zones"
  include_tasks: zones.yml
  when: firewalld_zones is defined

- name: "main | Include tasks for managing firewall rules"
  include_tasks: rules.yml
  when: firewalld_rules is defined
