---
- name: "redhat | Installing Firewalld (!=Fedora)"
  ansible.builtin.yum:
    name: "firewalld"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

- name: "redhat | Installing Firewalld (==Fedora)"
  ansible.builtin.dnf:
    name:
      - 'firewall-config'
      - 'firewalld'
      - 'python-firewall'
    state: "present"
  become: true
  when: ansible_distribution == "Fedora"

- name: "redhat | Ensuring firewalld service is enabled on boot"
  ansible.builtin.service:
    name: "firewalld"
    enabled: true
  become: true
